// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type CreateProjectReq struct {
	UserId      int64  `json:"userId"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type DeleteProjectReq struct {
	Id int64 `path:"id"`
}

type FileVersionItem struct {
	Id            int64  `json:"id"`
	FileId        int64  `json:"fileId"`
	VersionNumber int64  `json:"versionNumber"`
	SizeBytes     int64  `json:"sizeBytes"`
	Hash          string `json:"hash"`
	StorageKey    string `json:"storageKey"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
	CreatedBy     int64  `json:"createdBy"`
}

type FileVersionListResp struct {
	List []FileVersionItem `json:"list"`
	Page PageResp          `json:"page"`
}

type GetProjectReq struct {
	Id int64 `path:"id"`
}

type GetUserByEmailReq struct {
	Email string `path:"email"`
}

type InviteMemberReq struct {
	UserId        int64  `json:"userId"`        // 发起者
	InvitedUserId int64  `json:"invitedUserId"` // 被邀请者
	ProjectId     int64  `path:"id"`
	Role          string `json:"role"` // owner | admin | developer | viewer
}

type ListFileVersionsReq struct {
	Id       int64 `path:"id"`
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}

type ListProjectFilesReq struct {
	ProjectId int64 `path:"projectId"`
	Page      int64 `form:"page,default=1"`
	PageSize  int64 `form:"pageSize,default=20"`
}

type LoginReq struct {
	LoginType string `json:"loginType"` // email | google
	Email     string `json:"email,optional"`
	Password  string `json:"password,optional"`
	IdToken   string `json:"idToken,optional"`
}

type LoginResp struct {
	UserId  int64  `json:"userId"`
	Created bool   `json:"created"` // 如果是注册逻辑则为 true
	Token   string `json:"token"`
}

type PageReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}

type PageResp struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
	Total    int64 `json:"total"`
}

type PreUploadReq struct {
	ProjectId    int64  `json:"projectId"`
	Name         string `json:"name"`
	FileCategory string `json:"fileCategory"` // text | image | video | audio | binary | archive
	FileFormat   string `json:"fileFormat"`   // 文件格式，如 png, jpg, mp4, mp3, txt 等
	SizeBytes    int64  `json:"sizeBytes"`
	Hash         string `json:"hash"`
	ContentType  string `json:"contentType"`  // 上传文件的 Content-Type，如 text/plain, image/png 等
}

type PreUploadResp struct {
	UploadUrl     string `json:"uploadUrl"`
	FileId        int64  `json:"fileId"`
	VersionId     int64  `json:"versionId"`
	VersionNumber int64  `json:"versionNumber"`
	ContentType   string `json:"contentType"` // 上传时必须使用的 Content-Type
}

type ProjectFileItem struct {
	Id               int64  `json:"id"`
	ProjectId        int64  `json:"projectId"`
	Name             string `json:"name"`
	FileCategory     string `json:"fileCategory"`
	FileFormat       string `json:"fileFormat"`
	CurrentVersionId int64  `json:"currentVersionId"`
	VersionId        int64  `json:"versionId"`
	VersionNumber    int64  `json:"versionNumber"`
	SizeBytes        int64  `json:"sizeBytes"`
	Hash             string `json:"hash"`
	CreatedAt        string `json:"createdAt"`
	StorageKey       string `json:"storageKey"`
}

type ProjectFileListResp struct {
	List []ProjectFileItem `json:"list"`
	Page PageResp          `json:"page"`
}

type ProjectListResp struct {
	List []ProjectResp `json:"list"`
	Page PageResp      `json:"page"`
}

type ProjectResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	OwnerId     int64  `json:"ownerId"`
	Status      string `json:"status"` // active | archived
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type UpdateProjectReq struct {
	Id          int64  `path:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      string `json:"status"` // active | archived
}

type UpdateUserReq struct {
	Id       int64  `path:"id"`
	Username string `json:"username"`
}

type UserInfoResp struct {
	Id           int64  `json:"id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"passwordHash"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type UserListResp struct {
	List []UserInfoResp `json:"list"`
	Page PageResp       `json:"page"`
}
