// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResp struct {
	Code int32
	Msg  string
}

type CreateProjectReq struct {
	UserId      int64
	Name        string
	Description string
}

type DeleteProjectReq struct {
	Id int64
}

type FileVersionItem struct {
	Id            int64
	FileId        int64
	VersionNumber int64
	SizeBytes     int64
	Hash          string
	StoragePath   string
	MimeType      string
	CreatedAt     string
	UpdatedAt     string
	CreatedBy     int64
}

type FileVersionListResp struct {
	List []FileVersionItem
	Page PageResp
}

type GetProjectReq struct {
	Id int64
}

type GetUserByEmailReq struct {
	Email string
}

type InviteMemberReq struct {
	UserId        int64 // 发起者
	InvitedUserId int64 // 被邀请者
	ProjectId     int64
	Role          string // owner | admin | developer | viewer
}

type ListFileVersionsReq struct {
	Id       int64
	Page     int64
	PageSize int64
}

type ListProjectFilesReq struct {
	ProjectId int64
	Page      int64
	PageSize  int64
}

type LoginReq struct {
	Email    string
	Password string
}

type LoginResp struct {
	UserId  int64
	Created bool // 如果是注册逻辑则为 true
}

type PageReq struct {
	Page     int64 //(default:1)
	PageSize int64 //(default:20)
}

type PageResp struct {
	Page     int64
	PageSize int64
	Total    int64
}

type PreUploadReq struct {
	ProjectId    int64
	Name         string
	FileCategory string // text | image | video | audio | binary
	SizeBytes    int64
	Hash         string
	MimeType     string
}

type PreUploadResp struct {
	UploadUrl     string
	FileId        int64
	VersionId     int64
	VersionNumber int64
}

type ProjectFileItem struct {
	Id            int64
	ProjectId     int64
	Name          string
	FileCategory  string
	VersionId     int64
	VersionNumber int64
	SizeBytes     int64
	Hash          string
	MimeType      string
	CreatedAt     string
	StoragePath   string
}

type ProjectFileListResp struct {
	List []ProjectFileItem
	Page PageResp
}

type ProjectListResp struct {
	List []ProjectResp
	Page PageResp
}

type ProjectResp struct {
	Id          int64
	Name        string
	Description string
	OwnerId     int64
	Status      string // active | archived
	CreatedAt   string
	UpdatedAt   string
}

type UpdateProjectReq struct {
	Id          int64
	Name        string
	Description string
	Status      string // active | archived
}

type UpdateUserReq struct {
	Id       int64
	Username string
}

type UserInfoResp struct {
	Id           int64
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    string
	UpdatedAt    string
}

type UserListResp struct {
	List []UserInfoResp
	Page PageResp
}
