// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AdminCreateProjectReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	OwnerId     int64  `json:"ownerId"`
}

type AdminCreateUserReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type AdminDeleteProjectReq struct {
	Id int64 `path:"id"`
}

type AdminDeleteUserReq struct {
	Id int64 `path:"id"`
}

type AdminInfoResp struct {
	Id          int64  `json:"id"`
	Username    string `json:"username"`
	Role        string `json:"role"`
	Status      string `json:"status"`
	LastLoginAt string `json:"lastLoginAt"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type AdminListResp struct {
	List []AdminInfoResp `json:"list"`
	Page PageResp        `json:"page"`
}

type AdminLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AdminLoginResp struct {
	AdminId int64  `json:"adminId"`
	Role    string `json:"role"`
	Token   string `json:"token"`
}

type AdminUpdateProjectReq struct {
	Id          int64  `path:"id"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	Status      string `json:"status,optional"` // active | archived
}

type AdminUpdateUserReq struct {
	Id       int64  `path:"id"`
	Username string `json:"username,optional"`
	Email    string `json:"email,optional"`
	Password string `json:"password,optional"`
}

type BaseResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type CreateAdminReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Role     string `json:"role,default=admin"` // super_admin | admin
}

type CreateProjectReq struct {
	UserId      int64  `json:"userId"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CreateSoftwareTemplateReq struct {
	Name          string `json:"name"`
	Description   string `json:"description,optional"`
	ArchiveFileId int64  `json:"archiveFileId,optional"`
}

type DeleteAdminReq struct {
	Id int64 `path:"id"`
}

type DeleteFileReq struct {
	Id int64 `path:"id"`
}

type DeleteProjectReq struct {
	Id int64 `path:"id"`
}

type DeleteSoftwareTemplateReq struct {
	Id int64 `path:"id"`
}

type DownloadFileReq struct {
	Id            int64 `path:"id"`
	VersionId     int64 `form:"versionId,optional"`
	VersionNumber int64 `form:"versionNumber,optional"`
}

type DownloadFileResp struct {
	DownloadUrl string `json:"downloadUrl"`
	ExpiresAt   string `json:"expiresAt"`
}

type FileVersionItem struct {
	Id            int64  `json:"id"`
	FileId        int64  `json:"fileId"`
	VersionNumber int64  `json:"versionNumber"`
	SizeBytes     int64  `json:"sizeBytes"`
	Hash          string `json:"hash"`
	StorageKey    string `json:"storageKey"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
	CreatedBy     int64  `json:"createdBy"`
}

type FileVersionListResp struct {
	List []FileVersionItem `json:"list"`
	Page PageResp          `json:"page"`
}

type GetFileContentReq struct {
	Id int64 `path:"id"`
}

type GetProjectReq struct {
	Id int64 `path:"id"`
}

type GetSoftwareTemplateReq struct {
	Id int64 `path:"id"`
}

type GetUserByEmailReq struct {
	Email string `path:"email"`
}

type InviteMemberReq struct {
	UserId        int64  `json:"userId"`        // 发起者
	InvitedUserId int64  `json:"invitedUserId"` // 被邀请者
	ProjectId     int64  `path:"id"`
	Role          string `json:"role"` // owner | admin | developer | viewer
}

type ListAdminsReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}

type ListFileVersionsReq struct {
	Id       int64 `path:"id"`
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}

type ListProjectFilesReq struct {
	ProjectId int64 `path:"projectId"`
	Page      int64 `form:"page,default=1"`
	PageSize  int64 `form:"pageSize,default=20"`
}

type LoginReq struct {
	LoginType string `json:"loginType"` // email | google
	Email     string `json:"email,optional"`
	Password  string `json:"password,optional"`
	IdToken   string `json:"idToken,optional"`
}

type LoginResp struct {
	UserId  int64  `json:"userId"`
	Created bool   `json:"created"` // 如果是注册逻辑则为 true
	Token   string `json:"token"`
}

type PageReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}

type PageResp struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
	Total    int64 `json:"total"`
}

type PreUploadReq struct {
	ProjectId    int64  `json:"projectId"`
	Name         string `json:"name"`
	FileCategory string `json:"fileCategory"` // text | image | video | audio | binary | archive
	FileFormat   string `json:"fileFormat"`   // 文件格式，如 png, jpg, mp4, mp3, txt 等
	SizeBytes    int64  `json:"sizeBytes"`
	Hash         string `json:"hash"`
	ContentType  string `json:"contentType,optional"` // 上传文件的 Content-Type，如 text/plain, image/png 等
}

type PreUploadResp struct {
	UploadUrl     string `json:"uploadUrl"`
	FileId        int64  `json:"fileId"`
	VersionId     int64  `json:"versionId"`
	VersionNumber int64  `json:"versionNumber"`
	ContentType   string `json:"contentType"` // 上传时必须使用的 Content-Type
}

type ProjectFileItem struct {
	Id               int64  `json:"id"`
	ProjectId        int64  `json:"projectId"`
	Name             string `json:"name"`
	FileCategory     string `json:"fileCategory"`
	FileFormat       string `json:"fileFormat"`
	CurrentVersionId int64  `json:"currentVersionId"`
	VersionId        int64  `json:"versionId"`
	VersionNumber    int64  `json:"versionNumber"`
	SizeBytes        int64  `json:"sizeBytes"`
	Hash             string `json:"hash"`
	CreatedAt        string `json:"createdAt"`
	StorageKey       string `json:"storageKey"`
}

type ProjectFileListResp struct {
	List []ProjectFileItem `json:"list"`
	Page PageResp          `json:"page"`
}

type ProjectListResp struct {
	List []ProjectResp `json:"list"`
	Page PageResp      `json:"page"`
}

type ProjectResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CoverFileId int64  `json:"coverFileId"`
	OwnerId     int64  `json:"ownerId"`
	Status      string `json:"status"` // active | archived
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type RollbackVersionReq struct {
	Id            int64 `path:"id"`
	VersionNumber int64 `json:"versionNumber"`
}

type SoftwareTemplateListResp struct {
	List []SoftwareTemplateResp `json:"list"`
	Page PageResp               `json:"page"`
}

type SoftwareTemplateResp struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	ArchiveFileId int64  `json:"archiveFileId"`
	CreatedBy     int64  `json:"createdBy"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type UpdateAdminReq struct {
	Id       int64  `path:"id"`
	Password string `json:"password,optional"`
	Role     string `json:"role,optional"`   // super_admin | admin
	Status   string `json:"status,optional"` // active | disabled
}

type UpdateProjectReq struct {
	Id          int64  `path:"id"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	CoverFileId int64  `json:"coverFileId,optional"`
	Status      string `json:"status,optional"` // active | archived
}

type UpdateSoftwareTemplateReq struct {
	Id            int64  `path:"id"`
	Name          string `json:"name,optional"`
	Description   string `json:"description,optional"`
	ArchiveFileId int64  `json:"archiveFileId,optional"`
}

type UpdateUserReq struct {
	Id       int64  `path:"id"`
	Username string `json:"username"`
}

type UserInfoResp struct {
	Id           int64  `json:"id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"passwordHash"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type UserListResp struct {
	List []UserInfoResp `json:"list"`
	Page PageResp       `json:"page"`
}

type CreateLlmProviderReq struct {
	Name        string `json:"name"`
	BaseUrl     string `json:"baseUrl"`
	ApiKey      string `json:"apiKey,optional"`
	Description string `json:"description,optional"`
}

type UpdateLlmProviderReq struct {
	Id          int64  `path:"id"`
	Name        string `json:"name,optional"`
	BaseUrl     string `json:"baseUrl,optional"`
	ApiKey      string `json:"apiKey,optional"`
	ClearApiKey bool   `json:"clearApiKey,optional"`
	Description string `json:"description,optional"`
}

type DeleteLlmProviderReq struct {
	Id int64 `path:"id"`
}

type GetLlmProviderReq struct {
	Id int64 `path:"id"`
}

type LlmProviderResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	BaseUrl     string `json:"baseUrl"`
	HasApiKey   bool   `json:"hasApiKey"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type LlmProviderListResp struct {
	List []LlmProviderResp `json:"list"`
	Page PageResp          `json:"page"`
}

type CreateLlmModelReq struct {
	ProviderId       int64   `json:"providerId"`
	ModelName        string  `json:"modelName"`
	ModelType        string  `json:"modelType"` // llm | vlm | embedding
	MaxInputTokens   int64   `json:"maxInputTokens"`
	MaxOutputTokens  int64   `json:"maxOutputTokens"`
	SupportStream    bool    `json:"supportStream"`
	SupportJson      bool    `json:"supportJson"`
	PriceInputPer1k  float64 `json:"priceInputPer1k"`
	PriceOutputPer1k float64 `json:"priceOutputPer1k"`
}

type UpdateLlmModelReq struct {
	Id               int64    `path:"id"`
	ProviderId       *int64   `json:"providerId,optional"`
	ModelName        string   `json:"modelName,optional"`
	ModelType        string   `json:"modelType,optional"` // llm | vlm | embedding
	MaxInputTokens   *int64   `json:"maxInputTokens,optional"`
	MaxOutputTokens  *int64   `json:"maxOutputTokens,optional"`
	SupportStream    *bool    `json:"supportStream,optional"`
	SupportJson      *bool    `json:"supportJson,optional"`
	PriceInputPer1k  *float64 `json:"priceInputPer1k,optional"`
	PriceOutputPer1k *float64 `json:"priceOutputPer1k,optional"`
}

type DeleteLlmModelReq struct {
	Id int64 `path:"id"`
}

type GetLlmModelReq struct {
	Id int64 `path:"id"`
}

type ListLlmModelsReq struct {
	ProviderId int64  `form:"providerId,optional"`
	ModelType  string `form:"modelType,optional"` // llm | vlm | embedding
	Page       int64  `form:"page,default=1"`
	PageSize   int64  `form:"pageSize,default=20"`
}

type LlmModelResp struct {
	Id               int64   `json:"id"`
	ProviderId       int64   `json:"providerId"`
	ModelName        string  `json:"modelName"`
	ModelType        string  `json:"modelType"`
	MaxInputTokens   int64   `json:"maxInputTokens"`
	MaxOutputTokens  int64   `json:"maxOutputTokens"`
	SupportStream    bool    `json:"supportStream"`
	SupportJson      bool    `json:"supportJson"`
	PriceInputPer1k  float64 `json:"priceInputPer1k"`
	PriceOutputPer1k float64 `json:"priceOutputPer1k"`
	CreatedAt        string  `json:"createdAt"`
	UpdatedAt        string  `json:"updatedAt"`
}

type LlmModelListResp struct {
	List []LlmModelResp `json:"list"`
	Page PageResp       `json:"page"`
}

type ListLlmUsageLogsReq struct {
	ProjectId  int64 `form:"projectId,optional"`
	LlmModelId int64 `form:"llmModelId,optional"`
	Page       int64 `form:"page,default=1"`
	PageSize   int64 `form:"pageSize,default=20"`
}

type LlmUsageLogResp struct {
	Id           int64   `json:"id"`
	LlmModelId   int64   `json:"llmModelId"`
	ProjectId    int64   `json:"projectId"`
	InputTokens  int64   `json:"inputTokens"`
	OutputTokens int64   `json:"outputTokens"`
	CacheHit     bool    `json:"cacheHit"`
	CostUsd      float64 `json:"costUsd"`
	CreatedAt    string  `json:"createdAt"`
}

type LlmUsageLogListResp struct {
	List []LlmUsageLogResp `json:"list"`
	Page PageResp          `json:"page"`
}

type CreateAgentReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	AgentType   string `json:"agentType"` // code | asset | design | test | build | ops
}

type UpdateAgentReq struct {
	Id          int64  `path:"id"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	AgentType   string `json:"agentType,optional"` // code | asset | design | test | build | ops
}

type GetAgentReq struct {
	Id int64 `path:"id"`
}

type DeleteAgentReq struct {
	Id int64 `path:"id"`
}

type ListAgentsReq struct {
	AgentType string `form:"agentType,optional"` // code | asset | design | test | build | ops
	Page      int64  `form:"page,default=1"`
	PageSize  int64  `form:"pageSize,default=20"`
}

type AgentResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	AgentType   string `json:"agentType"`
	CreatedAt   string `json:"createdAt"`
}

type AgentListResp struct {
	List []AgentResp `json:"list"`
	Page PageResp    `json:"page"`
}

type ListAgentBindingsReq struct {
	AgentId int64 `path:"id"`
}

type CreateAgentBindingReq struct {
	AgentId    int64 `path:"id"`
	LlmModelId int64 `json:"llmModelId"`
	Priority   int64 `json:"priority,optional"`
	IsActive   *bool `json:"isActive,optional"`
}

type UpdateAgentBindingReq struct {
	Id         int64  `path:"id"`
	LlmModelId int64  `json:"llmModelId,optional"`
	Priority   *int64 `json:"priority,optional"`
	IsActive   *bool  `json:"isActive,optional"`
}

type DeleteAgentBindingReq struct {
	Id int64 `path:"id"`
}

type AgentBindingResp struct {
	Id           int64  `json:"id"`
	AgentId      int64  `json:"agentId"`
	LlmModelId   int64  `json:"llmModelId"`
	Priority     int64  `json:"priority"`
	IsActive     bool   `json:"isActive"`
	CreatedAt    string `json:"createdAt"`
	ProviderId   int64  `json:"providerId"`
	ProviderName string `json:"providerName"`
	ModelName    string `json:"modelName"`
	ModelType    string `json:"modelType"`
}

type AgentBindingListResp struct {
	List []AgentBindingResp `json:"list"`
}
