// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	admin "github.com/anil-wu/spark-x/internal/handler/admin"
	admin_auth "github.com/anil-wu/spark-x/internal/handler/admin_auth"
	auth "github.com/anil-wu/spark-x/internal/handler/auth"
	files "github.com/anil-wu/spark-x/internal/handler/files"
	projects "github.com/anil-wu/spark-x/internal/handler/projects"
	users "github.com/anil-wu/spark-x/internal/handler/users"
	"github.com/anil-wu/spark-x/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admins",
				Handler: admin.CreateAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admins",
				Handler: admin.ListAdminsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/admins/:id",
				Handler: admin.UpdateAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/admins/:id",
				Handler: admin.DeleteAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/profile",
				Handler: admin.AdminProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/projects",
				Handler: admin.AdminCreateProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/projects",
				Handler: admin.AdminListProjectsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/projects/:id",
				Handler: admin.AdminDeleteProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/projects/:id",
				Handler: admin.AdminUpdateProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/software-templates",
				Handler: admin.CreateSoftwareTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/software-templates",
				Handler: admin.ListSoftwareTemplatesHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/software-templates/:id",
				Handler: admin.UpdateSoftwareTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/software-templates/:id",
				Handler: admin.DeleteSoftwareTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/software-templates/:id",
				Handler: admin.GetSoftwareTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/llm/providers",
				Handler: admin.CreateLlmProviderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/llm/providers",
				Handler: admin.ListLlmProvidersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/llm/providers/:id",
				Handler: admin.GetLlmProviderHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/llm/providers/:id",
				Handler: admin.UpdateLlmProviderHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/llm/providers/:id",
				Handler: admin.DeleteLlmProviderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/llm/models",
				Handler: admin.CreateLlmModelHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/llm/models",
				Handler: admin.ListLlmModelsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/llm/models/:id",
				Handler: admin.GetLlmModelHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/llm/models/:id",
				Handler: admin.UpdateLlmModelHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/llm/models/:id",
				Handler: admin.DeleteLlmModelHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/llm/usage-logs",
				Handler: admin.ListLlmUsageLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/agents",
				Handler: admin.CreateAgentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/agents",
				Handler: admin.ListAgentsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/agents/:id",
				Handler: admin.GetAgentHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/agents/:id",
				Handler: admin.UpdateAgentHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/agents/:id",
				Handler: admin.DeleteAgentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/agents/:id/bindings",
				Handler: admin.ListAgentBindingsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/agents/:id/bindings",
				Handler: admin.CreateAgentBindingHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/agent-bindings/:id",
				Handler: admin.UpdateAgentBindingHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/agent-bindings/:id",
				Handler: admin.DeleteAgentBindingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/files/preupload",
				Handler: files.PreUploadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/files/:id/versions",
				Handler: files.ListFileVersionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/files/:id/download",
				Handler: files.DownloadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users",
				Handler: admin.AdminCreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users",
				Handler: admin.AdminListUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/users/:id",
				Handler: admin.AdminDeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/:id",
				Handler: admin.AdminUpdateUserHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.AdminAuth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: admin_auth.AdminLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/files/:id",
				Handler: files.DeleteFileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/files/:id/content",
				Handler: files.GetFileContentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/files/:id/download",
				Handler: files.DownloadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/files/:id/rollback",
				Handler: files.RollbackVersionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/files/:id/versions",
				Handler: files.ListFileVersionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/files/preupload",
				Handler: files.PreUploadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/projects/:projectId/files",
				Handler: files.ListProjectFilesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/projects",
				Handler: projects.CreateProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/projects",
				Handler: projects.ListProjectsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/projects/:id",
				Handler: projects.DeleteProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/projects/:id",
				Handler: projects.UpdateProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/projects/:id",
				Handler: projects.GetProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/projects/:id/invite",
				Handler: projects.InviteMemberHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/users",
				Handler: users.ListUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/:id",
				Handler: users.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/email/:email",
				Handler: users.GetUserByEmailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
