// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"errors"

	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	adminsFieldNames          = builder.RawFieldNames(&Admins{})
	adminsRows                = strings.Join(adminsFieldNames, ",")
	adminsRowsExpectAutoSet   = strings.Join(stringx.Remove(adminsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminsRowsWithPlaceHolder = strings.Join(stringx.Remove(adminsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	adminsModel interface {
		Insert(ctx context.Context, data *Admins) (int64, error)
		FindOne(ctx context.Context, id uint64) (*Admins, error)
		FindOneByUsername(ctx context.Context, username string) (*Admins, error)
		Update(ctx context.Context, id int64, data *Admins) (int64, error)
		Delete(ctx context.Context, id uint64) (int64, error)
	}

	defaultAdminsModel struct {
		DB    *gorm.DB
		conn  sqlx.SqlConn
		table string
	}

	Admins struct {
		Id           uint64       `db:"id" gorm:"column:id;primaryKey"`
		Username     string       `db:"username" gorm:"column:username"`
		PasswordHash string       `db:"password_hash" gorm:"column:password_hash"`
		Role         string       `db:"role" gorm:"column:role"`
		Status       string       `db:"status" gorm:"column:status"`
		LastLoginAt  sql.NullTime `db:"last_login_at" gorm:"column:last_login_at"`
		CreatedAt    time.Time    `db:"created_at" gorm:"column:created_at"`
		UpdatedAt    time.Time    `db:"updated_at" gorm:"column:updated_at"`
	}
)

func newAdminsModel(conn *gorm.DB, connS sqlx.SqlConn) *defaultAdminsModel {
	return &defaultAdminsModel{
		DB:    conn,
		conn:  connS,
		table: "`admins`",
	}
}

func (m *defaultAdminsModel) TableName() string {
	return m.table
}

func (m *defaultAdminsModel) Delete(ctx context.Context, id uint64) (int64, error) {
	logx.WithContext(ctx).Infof("delete data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("delete error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Delete(&Admins{})
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("delete error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

func (m *defaultAdminsModel) FindOne(ctx context.Context, id uint64) (*Admins, error) {
	logx.WithContext(ctx).Infof("findOne data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("findOne error:%+v", "param invalid")
		return nil, InputParamInvalid
	}

	var result Admins
	err := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOne error:%+v", err)
		return nil, ReadDataFailed
	}

	return &result, nil
}

func (m *defaultAdminsModel) FindOneByUsername(ctx context.Context, username string) (*Admins, error) {
	logx.WithContext(ctx).Infof("findOneByUsername data:%+v", username)

	if username == "" {
		logx.WithContext(ctx).Errorf("findOneByUsername error:%+v", "param invalid")
		return nil, InputParamInvalid
	}

	var result Admins
	err := m.DB.Debug().WithContext(ctx).Where("`username` = ?", username).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOneByUsername error:%+v", err)
		return nil, ReadDataFailed
	}

	return &result, nil
}

func (m *defaultAdminsModel) Insert(ctx context.Context, data *Admins) (int64, error) {
	logx.WithContext(ctx).Infof("insert data:%+v", data)

	if data == nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Create(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

func (m *defaultAdminsModel) Update(ctx context.Context, id int64, data *Admins) (int64, error) {
	logx.WithContext(ctx).Infof("update data:%+v", data)

	if id <= 0 || data == nil {
		logx.WithContext(ctx).Errorf("update error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Model(&Admins{}).Where("`id` = ?", id).Updates(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("update error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}
