// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"strings"
	"time"

	"errors"

	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	fileVersionsFieldNames          = builder.RawFieldNames(&FileVersions{})
	fileVersionsRows                = strings.Join(fileVersionsFieldNames, ",")
	fileVersionsRowsExpectAutoSet   = strings.Join(stringx.Remove(fileVersionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	fileVersionsRowsWithPlaceHolder = strings.Join(stringx.Remove(fileVersionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	fileVersionsModel interface {
		// 返回的是受影响行数，如需获取自增id，请通过data参数获取
		Insert(ctx context.Context, data *FileVersions) (int64, error)
		FindOne(ctx context.Context, id uint64) (*FileVersions, error)
		FindOneByFileIdVersionNumber(ctx context.Context, fileId uint64, versionNumber uint64) (*FileVersions, error)
		// 通过主键id更新指定字段，零值不可更新，返回受影响行数
		Update(ctx context.Context, id int64, data *FileVersions) (int64, error)
		// 通过主键id删除数据，返回受影响行数
		Delete(ctx context.Context, id uint64) (int64, error)
	}

	defaultFileVersionsModel struct {
		DB    *gorm.DB
		conn  sqlx.SqlConn
		table string
	}

	FileVersions struct {
		Id            uint64    `db:"id" gorm:"column:id;primaryKey"`
		FileId        uint64    `db:"file_id" gorm:"column:file_id"`
		VersionNumber uint64    `db:"version_number" gorm:"column:version_number"`
		SizeBytes     uint64    `db:"size_bytes" gorm:"column:size_bytes"`
		Hash          string    `db:"hash" gorm:"column:hash"`
		StoragePath   string    `db:"storage_path" gorm:"column:storage_path"`
		MimeType      string    `db:"mime_type" gorm:"column:mime_type"`
		CreatedAt     time.Time `db:"created_at" gorm:"column:created_at"`
		UpdatedAt     time.Time `db:"updated_at" gorm:"column:updated_at"`
		CreatedBy     uint64    `db:"created_by" gorm:"column:created_by"`
	}
)

func newFileVersionsModel(conn *gorm.DB, connS sqlx.SqlConn) *defaultFileVersionsModel {
	return &defaultFileVersionsModel{
		DB:    conn,
		conn:  connS,
		table: "`file_versions`",
	}
}

func (m *defaultFileVersionsModel) TableName() string {
	return m.table
}

// Delete 通过主键id删除数据，返回受影响行数
func (m *defaultFileVersionsModel) Delete(ctx context.Context, id uint64) (int64, error) {
	logx.WithContext(ctx).Infof("delete data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("delete error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Delete(&FileVersions{})
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("delete error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

// FindOne 通过主键id查找数据
func (m *defaultFileVersionsModel) FindOne(ctx context.Context, id uint64) (*FileVersions, error) {
	logx.WithContext(ctx).Infof("findOne data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("findOne error:%+v", "param invalid")
		return nil, InputParamInvalid
	}

	var result FileVersions
	err := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOne error:%+v", err)
		return nil, ReadDataFailed
	}
	return &result, nil

}

// FindOneByFileIdVersionNumber 通过指定字段查找数据
func (m *defaultFileVersionsModel) FindOneByFileIdVersionNumber(ctx context.Context, fileId uint64, versionNumber uint64) (*FileVersions, error) {
	logx.WithContext(ctx).Infof("findOneByFileIdVersionNumber data:%+v", fileId, versionNumber)

	var result FileVersions
	err := m.DB.Debug().WithContext(ctx).Where("`file_id` = ? and `version_number` = ?", fileId, versionNumber).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOneByFileIdVersionNumber error:%+v", err)
		return nil, err
	}
	return &result, nil

}

// Insert 返回的是受影响行数，如需获取自增id，请通过data参数获取
func (m *defaultFileVersionsModel) Insert(ctx context.Context, data *FileVersions) (int64, error) {
	logx.WithContext(ctx).Infof("insert data:%+v", data)
	if data == nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", "param invalid")
		return 0, InputParamInvalid
	}
	result := m.DB.Debug().WithContext(ctx).Create(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

// Update 通过主键id更新指定字段，零值不可更新，返回受影响行数
func (m *defaultFileVersionsModel) Update(ctx context.Context, id int64, data *FileVersions) (int64, error) {
	logx.WithContext(ctx).Infof("update data:%+v", data)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("update error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Updates(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("update error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

func (m *defaultFileVersionsModel) tableName() string {
	return m.table
}
