// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"strings"
	"time"

	"errors"

	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	filesFieldNames          = builder.RawFieldNames(&Files{})
	filesRows                = strings.Join(filesFieldNames, ",")
	filesRowsExpectAutoSet   = strings.Join(stringx.Remove(filesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	filesRowsWithPlaceHolder = strings.Join(stringx.Remove(filesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	filesModel interface {
		// 返回的是受影响行数，如需获取自增id，请通过data参数获取
		Insert(ctx context.Context, data *Files) (int64, error)
		FindOne(ctx context.Context, id uint64) (*Files, error)
		FindOneByProjectIdName(ctx context.Context, projectId uint64, name string) (*Files, error)
		// 通过主键id更新指定字段，零值不可更新，返回受影响行数
		Update(ctx context.Context, id int64, data *Files) (int64, error)
		// 通过主键id删除数据，返回受影响行数
		Delete(ctx context.Context, id uint64) (int64, error)
	}

	defaultFilesModel struct {
		DB    *gorm.DB
		conn  sqlx.SqlConn
		table string
	}

	Files struct {
		Id               uint64         `db:"id" gorm:"column:id;primaryKey"`
		ProjectId        uint64         `db:"project_id" gorm:"column:project_id"`
		Name             string         `db:"name" gorm:"column:name"`
		FileCategory     string         `db:"file_category" gorm:"column:file_category"`
		FileFormat       string         `db:"file_format" gorm:"column:file_format"`
		CurrentVersionId uint64         `db:"current_version_id" gorm:"column:current_version_id"`
		CreatedAt        time.Time      `db:"created_at" gorm:"column:created_at"`
		DeletedAt        gorm.DeletedAt `db:"deleted_at" gorm:"column:deleted_at;index"`
	}
)

func newFilesModel(conn *gorm.DB, connS sqlx.SqlConn) *defaultFilesModel {
	return &defaultFilesModel{
		DB:    conn,
		conn:  connS,
		table: "`files`",
	}
}

func (m *defaultFilesModel) TableName() string {
	return m.table
}

// Delete 通过主键id删除数据，返回受影响行数
func (m *defaultFilesModel) Delete(ctx context.Context, id uint64) (int64, error) {
	logx.WithContext(ctx).Infof("delete data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("delete error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Delete(&Files{})
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("delete error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

// FindOne 通过主键id查找数据
func (m *defaultFilesModel) FindOne(ctx context.Context, id uint64) (*Files, error) {
	logx.WithContext(ctx).Infof("findOne data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("findOne error:%+v", "param invalid")
		return nil, InputParamInvalid
	}

	var result Files
	err := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOne error:%+v", err)
		return nil, ReadDataFailed
	}
	return &result, nil

}

// FindOneByProjectIdName 通过指定字段查找数据
func (m *defaultFilesModel) FindOneByProjectIdName(ctx context.Context, projectId uint64, name string) (*Files, error) {
	logx.WithContext(ctx).Infof("findOneByProjectIdName data:%+v", projectId, name)

	var result Files
	err := m.DB.Debug().WithContext(ctx).Where("`project_id` = ? and `name` = ?", projectId, name).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOneByProjectIdName error:%+v", err)
		return nil, err
	}
	return &result, nil

}

// Insert 返回的是受影响行数，如需获取自增id，请通过data参数获取
func (m *defaultFilesModel) Insert(ctx context.Context, data *Files) (int64, error) {
	logx.WithContext(ctx).Infof("insert data:%+v", data)
	if data == nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", "param invalid")
		return 0, InputParamInvalid
	}
	result := m.DB.Debug().WithContext(ctx).Create(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

// Update 通过主键id更新指定字段，零值不可更新，返回受影响行数
func (m *defaultFilesModel) Update(ctx context.Context, id int64, data *Files) (int64, error) {
	logx.WithContext(ctx).Infof("update data:%+v", data)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("update error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Updates(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("update error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

func (m *defaultFilesModel) tableName() string {
	return m.table
}
