// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"strings"
	"time"

	"errors"

	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	projectFilesFieldNames          = builder.RawFieldNames(&ProjectFiles{})
	projectFilesRows                = strings.Join(projectFilesFieldNames, ",")
	projectFilesRowsExpectAutoSet   = strings.Join(stringx.Remove(projectFilesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	projectFilesRowsWithPlaceHolder = strings.Join(stringx.Remove(projectFilesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	projectFilesModel interface {
		// 返回的是受影响行数，如需获取自增id，请通过data参数获取
		Insert(ctx context.Context, data *ProjectFiles) (int64, error)
		FindOne(ctx context.Context, id uint64) (*ProjectFiles, error)
		FindOneByProjectIdFileId(ctx context.Context, projectId uint64, fileId uint64) (*ProjectFiles, error)
		// 通过主键id更新指定字段，零值不可更新，返回受影响行数
		Update(ctx context.Context, id int64, data *ProjectFiles) (int64, error)
		// 通过主键id删除数据，返回受影响行数
		Delete(ctx context.Context, id uint64) (int64, error)
	}

	defaultProjectFilesModel struct {
		DB    *gorm.DB
		conn  sqlx.SqlConn
		table string
	}

	ProjectFiles struct {
		Id        uint64    `db:"id" gorm:"column:id;primaryKey"`
		ProjectId uint64    `db:"project_id" gorm:"column:project_id"`
		FileId    uint64    `db:"file_id" gorm:"column:file_id"`
		CreatedAt time.Time `db:"created_at" gorm:"column:created_at"`
	}
)

func newProjectFilesModel(conn *gorm.DB, connS sqlx.SqlConn) *defaultProjectFilesModel {
	return &defaultProjectFilesModel{
		DB:    conn,
		conn:  connS,
		table: "`project_files`",
	}
}

func (m *defaultProjectFilesModel) TableName() string {
	return m.table
}

// Delete 通过主键id删除数据，返回受影响行数
func (m *defaultProjectFilesModel) Delete(ctx context.Context, id uint64) (int64, error) {
	logx.WithContext(ctx).Infof("delete data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("delete error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Delete(&ProjectFiles{})
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("delete error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

// FindOne 通过主键id查找数据
func (m *defaultProjectFilesModel) FindOne(ctx context.Context, id uint64) (*ProjectFiles, error) {
	logx.WithContext(ctx).Infof("findOne data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("findOne error:%+v", "param invalid")
		return nil, InputParamInvalid
	}

	var result ProjectFiles
	err := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOne error:%+v", err)
		return nil, ReadDataFailed
	}
	return &result, nil

}

// FindOneByProjectIdFileId 通过指定字段查找数据
func (m *defaultProjectFilesModel) FindOneByProjectIdFileId(ctx context.Context, projectId uint64, fileId uint64) (*ProjectFiles, error) {
	logx.WithContext(ctx).Infof("findOneByProjectIdFileId data:%+v", projectId, fileId)

	var result ProjectFiles
	err := m.DB.Debug().WithContext(ctx).Where("`project_id` = ? and `file_id` = ?", projectId, fileId).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOneByProjectIdFileId error:%+v", err)
		return nil, err
	}
	return &result, nil

}

// Insert 返回的是受影响行数，如需获取自增id，请通过data参数获取
func (m *defaultProjectFilesModel) Insert(ctx context.Context, data *ProjectFiles) (int64, error) {
	logx.WithContext(ctx).Infof("insert data:%+v", data)
	if data == nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", "param invalid")
		return 0, InputParamInvalid
	}
	result := m.DB.Debug().WithContext(ctx).Create(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

// Update 通过主键id更新指定字段，零值不可更新，返回受影响行数
func (m *defaultProjectFilesModel) Update(ctx context.Context, id int64, data *ProjectFiles) (int64, error) {
	logx.WithContext(ctx).Infof("update data:%+v", data)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("update error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Updates(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("update error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

func (m *defaultProjectFilesModel) tableName() string {
	return m.table
}
