// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"errors"

	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	softwareTemplatesFieldNames          = builder.RawFieldNames(&SoftwareTemplates{})
	softwareTemplatesRows                = strings.Join(softwareTemplatesFieldNames, ",")
	softwareTemplatesRowsExpectAutoSet   = strings.Join(stringx.Remove(softwareTemplatesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	softwareTemplatesRowsWithPlaceHolder = strings.Join(stringx.Remove(softwareTemplatesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	softwareTemplatesModel interface {
		// 返回的是受影响行数，如需获取自增id，请通过data参数获取
		Insert(ctx context.Context, data *SoftwareTemplates) (int64, error)
		FindOne(ctx context.Context, id uint64) (*SoftwareTemplates, error)
		// 通过主键id更新指定字段，零值不可更新，返回受影响行数
		Update(ctx context.Context, id int64, data *SoftwareTemplates) (int64, error)
		// 通过主键id删除数据，返回受影响行数
		Delete(ctx context.Context, id uint64) (int64, error)
	}

	defaultSoftwareTemplatesModel struct {
		DB    *gorm.DB
		conn  sqlx.SqlConn
		table string
	}

	SoftwareTemplates struct {
		Id            uint64         `db:"id" gorm:"column:id;primaryKey"`
		Name          string         `db:"name" gorm:"column:name"`
		Description   sql.NullString `db:"description" gorm:"column:description"`
		ArchiveFileId uint64         `db:"archive_file_id" gorm:"column:archive_file_id"`
		CreatedBy     uint64         `db:"created_by" gorm:"column:created_by"`
		CreatedAt     time.Time      `db:"created_at" gorm:"column:created_at"`
		UpdatedAt     time.Time      `db:"updated_at" gorm:"column:updated_at"`
	}
)

func newSoftwareTemplatesModel(conn *gorm.DB, connS sqlx.SqlConn) *defaultSoftwareTemplatesModel {
	return &defaultSoftwareTemplatesModel{
		DB:    conn,
		conn:  connS,
		table: "`software_templates`",
	}
}

func (m *defaultSoftwareTemplatesModel) TableName() string {
	return m.table
}

// Delete 通过主键id删除数据，返回受影响行数
func (m *defaultSoftwareTemplatesModel) Delete(ctx context.Context, id uint64) (int64, error) {
	logx.WithContext(ctx).Infof("delete data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("delete error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Delete(&SoftwareTemplates{})
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("delete error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

// FindOne 通过主键id查找数据
func (m *defaultSoftwareTemplatesModel) FindOne(ctx context.Context, id uint64) (*SoftwareTemplates, error) {
	logx.WithContext(ctx).Infof("findOne data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("findOne error:%+v", "param invalid")
		return nil, InputParamInvalid
	}

	var result SoftwareTemplates
	err := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOne error:%+v", err)
		return nil, ReadDataFailed
	}
	return &result, nil

}

// Insert 返回的是受影响行数，如需获取自增id，请通过data参数获取
func (m *defaultSoftwareTemplatesModel) Insert(ctx context.Context, data *SoftwareTemplates) (int64, error) {
	logx.WithContext(ctx).Infof("insert data:%+v", data)
	if data == nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", "param invalid")
		return 0, InputParamInvalid
	}
	result := m.DB.Debug().WithContext(ctx).Create(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

// Update 通过主键id更新指定字段，零值不可更新，返回受影响行数
func (m *defaultSoftwareTemplatesModel) Update(ctx context.Context, id int64, data *SoftwareTemplates) (int64, error) {
	logx.WithContext(ctx).Infof("update data:%+v", data)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("update error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Updates(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("update error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

func (m *defaultSoftwareTemplatesModel) tableName() string {
	return m.table
}
