// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"strings"
	"time"

	"errors"

	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	usersFieldNames          = builder.RawFieldNames(&Users{})
	usersRows                = strings.Join(usersFieldNames, ",")
	usersRowsExpectAutoSet   = strings.Join(stringx.Remove(usersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	usersRowsWithPlaceHolder = strings.Join(stringx.Remove(usersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	usersModel interface {
		// 返回的是受影响行数，如需获取自增id，请通过data参数获取
		Insert(ctx context.Context, data *Users) (int64, error)
		FindOne(ctx context.Context, id uint64) (*Users, error)
		FindOneByEmail(ctx context.Context, email string) (*Users, error)
		// 通过主键id更新指定字段，零值不可更新，返回受影响行数
		Update(ctx context.Context, id int64, data *Users) (int64, error)
		// 通过主键id删除数据，返回受影响行数
		Delete(ctx context.Context, id uint64) (int64, error)
	}

	defaultUsersModel struct {
		DB    *gorm.DB
		conn  sqlx.SqlConn
		table string
	}

	Users struct {
		Id           uint64    `db:"id"`
		Username     string    `db:"username"`
		Email        string    `db:"email"`
		PasswordHash string    `db:"password_hash"`
		CreatedAt    time.Time `db:"created_at"`
		UpdatedAt    time.Time `db:"updated_at"`
	}
)

func newUsersModel(conn *gorm.DB, connS sqlx.SqlConn) *defaultUsersModel {
	return &defaultUsersModel{
		DB:    conn,
		conn:  connS,
		table: "`users`",
	}
}

// Delete 通过主键id删除数据，返回受影响行数
func (m *defaultUsersModel) Delete(ctx context.Context, id uint64) (int64, error) {
	logx.WithContext(ctx).Infof("delete data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("delete error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Delete(&Users{})
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("delete error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

// FindOne 通过主键id查找数据
func (m *defaultUsersModel) FindOne(ctx context.Context, id uint64) (*Users, error) {
	logx.WithContext(ctx).Infof("findOne data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("findOne error:%+v", "param invalid")
		return nil, InputParamInvalid
	}

	var result Users
	err := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOne error:%+v", err)
		return nil, ReadDataFailed
	}
	return &result, nil

}

// FindOneByEmail 通过指定字段查找数据
func (m *defaultUsersModel) FindOneByEmail(ctx context.Context, email string) (*Users, error) {
	logx.WithContext(ctx).Infof("findOneByEmail data:%+v", email)

	var result Users
	err := m.DB.Debug().WithContext(ctx).Where("`email` = ?", email).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOneByEmail error:%+v", err)
		return nil, err
	}
	return &result, nil

}

// Insert 返回的是受影响行数，如需获取自增id，请通过data参数获取
func (m *defaultUsersModel) Insert(ctx context.Context, data *Users) (int64, error) {
	logx.WithContext(ctx).Infof("insert data:%+v", data)
	if data == nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", "param invalid")
		return 0, InputParamInvalid
	}
	result := m.DB.Debug().WithContext(ctx).Create(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

// Update 通过主键id更新指定字段，零值不可更新，返回受影响行数
func (m *defaultUsersModel) Update(ctx context.Context, id int64, data *Users) (int64, error) {
	logx.WithContext(ctx).Infof("update data:%+v", data)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("update error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Updates(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("update error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

func (m *defaultUsersModel) tableName() string {
	return m.table
}
