// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"strings"
	"time"

	"errors"

	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var (
	userIdentitiesFieldNames          = builder.RawFieldNames(&UserIdentities{})
	userIdentitiesRows                = strings.Join(userIdentitiesFieldNames, ",")
	userIdentitiesRowsExpectAutoSet   = strings.Join(stringx.Remove(userIdentitiesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userIdentitiesRowsWithPlaceHolder = strings.Join(stringx.Remove(userIdentitiesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userIdentitiesModel interface {
		Insert(ctx context.Context, data *UserIdentities) (int64, error)
		FindOne(ctx context.Context, id uint64) (*UserIdentities, error)
		FindOneByProviderProviderUid(ctx context.Context, provider string, providerUid string) (*UserIdentities, error)
		Update(ctx context.Context, id int64, data *UserIdentities) (int64, error)
		Delete(ctx context.Context, id uint64) (int64, error)
	}

	defaultUserIdentitiesModel struct {
		DB    *gorm.DB
		conn  sqlx.SqlConn
		table string
	}

	UserIdentities struct {
		Id          uint64    `db:"id" gorm:"column:id;primaryKey"`
		UserId      uint64    `db:"user_id" gorm:"column:user_id"`
		Provider    string    `db:"provider" gorm:"column:provider"`
		ProviderUid string    `db:"provider_uid" gorm:"column:provider_uid"`
		Email       string    `db:"email" gorm:"column:email"`
		CreatedAt   time.Time `db:"created_at" gorm:"column:created_at"`
		UpdatedAt   time.Time `db:"updated_at" gorm:"column:updated_at"`
	}
)

func newUserIdentitiesModel(conn *gorm.DB, connS sqlx.SqlConn) *defaultUserIdentitiesModel {
	return &defaultUserIdentitiesModel{
		DB:    conn,
		conn:  connS,
		table: "`user_identities`",
	}
}

func (m *defaultUserIdentitiesModel) TableName() string {
	return m.table
}

func (m *defaultUserIdentitiesModel) Insert(ctx context.Context, data *UserIdentities) (int64, error) {
	logx.WithContext(ctx).Infof("insert data:%+v", data)
	if data == nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", "param invalid")
		return 0, InputParamInvalid
	}
	result := m.DB.Debug().WithContext(ctx).Create(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", result.Error)
		return 0, WriteDataFailed
	}
	return result.RowsAffected, nil
}

func (m *defaultUserIdentitiesModel) FindOne(ctx context.Context, id uint64) (*UserIdentities, error) {
	logx.WithContext(ctx).Infof("findOne data:%+v", id)
	if id <= 0 {
		logx.WithContext(ctx).Errorf("findOne error:%+v", "param invalid")
		return nil, InputParamInvalid
	}
	var result UserIdentities
	err := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOne error:%+v", err)
		return nil, ReadDataFailed
	}
	return &result, nil
}

func (m *defaultUserIdentitiesModel) FindOneByProviderProviderUid(ctx context.Context, provider string, providerUid string) (*UserIdentities, error) {
	logx.WithContext(ctx).Infof("findOneByProviderProviderUid data:%+v, %+v", provider, providerUid)
	var result UserIdentities
	err := m.DB.Debug().WithContext(ctx).Where("`provider` = ? and `provider_uid` = ?", provider, providerUid).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOneByProviderProviderUid error:%+v", err)
		return nil, err
	}
	return &result, nil
}

func (m *defaultUserIdentitiesModel) Update(ctx context.Context, id int64, data *UserIdentities) (int64, error) {
	logx.WithContext(ctx).Infof("update data:%+v", data)
	if id <= 0 {
		logx.WithContext(ctx).Errorf("update error:%+v", "param invalid")
		return 0, InputParamInvalid
	}
	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Updates(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("update error:%+v", result.Error)
		return 0, WriteDataFailed
	}
	return result.RowsAffected, nil
}

func (m *defaultUserIdentitiesModel) Delete(ctx context.Context, id uint64) (int64, error) {
	logx.WithContext(ctx).Infof("delete data:%+v", id)
	if id <= 0 {
		logx.WithContext(ctx).Errorf("delete error:%+v", "param invalid")
		return 0, InputParamInvalid
	}
	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Delete(&UserIdentities{})
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("delete error:%+v", result.Error)
		return 0, WriteDataFailed
	}
	return result.RowsAffected, nil
}
