// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"errors"

	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var _ WorkspaceLayerModel = (*customWorkspaceLayerModel)(nil)

type (
	// WorkspaceLayerModel is an interface to be customized, add more methods here,
	// and implement the added methods in customWorkspaceLayerModel.
	WorkspaceLayerModel interface {
		workspaceLayerModel
	}

	customWorkspaceLayerModel struct {
		*defaultWorkspaceLayerModel
	}
)

// NewWorkspaceLayerModel returns a model for the database table.
func NewWorkspaceLayerModel(conn *gorm.DB, connS sqlx.SqlConn) WorkspaceLayerModel {
	return &customWorkspaceLayerModel{
		defaultWorkspaceLayerModel: newWorkspaceLayerModel(conn, connS),
	}
}

var (
	workspaceLayerFieldNames          = builder.RawFieldNames(&WorkspaceLayer{})
	workspaceLayerRows                = strings.Join(workspaceLayerFieldNames, ",")
	workspaceLayerRowsExpectAutoSet   = strings.Join(stringx.Remove(workspaceLayerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workspaceLayerRowsWithPlaceHolder = strings.Join(stringx.Remove(workspaceLayerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	workspaceLayerModel interface {
		// 返回的是受影响行数，如需获取自增 id，请通过 data 参数获取
		Insert(ctx context.Context, data *WorkspaceLayer) (int64, error)
		FindOne(ctx context.Context, id uint64) (*WorkspaceLayer, error)
		FindByCanvasId(ctx context.Context, canvasId uint64) ([]*WorkspaceLayer, error)
		FindDeletedByCanvasId(ctx context.Context, canvasId uint64, limit int64) ([]*WorkspaceLayer, error)
		// 通过主键 id 更新指定字段，零值不可更新，返回受影响行数
		Update(ctx context.Context, id int64, data *WorkspaceLayer) (int64, error)
		// 软删除
		SoftDelete(ctx context.Context, id uint64, deletedBy uint64) (int64, error)
		// 恢复已删除的数据
		Restore(ctx context.Context, id uint64) (int64, error)
		// 通过主键 id 删除数据，返回受影响行数
		Delete(ctx context.Context, id uint64) (int64, error)
	}

	defaultWorkspaceLayerModel struct {
		DB    *gorm.DB
		conn  sqlx.SqlConn
		table string
	}

	WorkspaceLayer struct {
		Id         uint64        `db:"id" gorm:"column:id;primaryKey"`
		CanvasId   uint64        `db:"canvas_id" gorm:"column:canvas_id"`
		LayerType  string        `db:"layer_type" gorm:"column:layer_type"`
		Name       string        `db:"name" gorm:"column:name"`
		ZIndex     int32         `db:"z_index" gorm:"column:z_index"`
		PositionX  float64       `db:"position_x" gorm:"column:position_x"`
		PositionY  float64       `db:"position_y" gorm:"column:position_y"`
		Width      float64       `db:"width" gorm:"column:width"`
		Height     float64       `db:"height" gorm:"column:height"`
		Rotation   float64       `db:"rotation" gorm:"column:rotation"`
		Visible    bool          `db:"visible" gorm:"column:visible"`
		Locked     bool          `db:"locked" gorm:"column:locked"`
		Deleted    bool          `db:"deleted" gorm:"column:deleted"`
		DeletedAt  sql.NullTime  `db:"deleted_at" gorm:"column:deleted_at"`
		DeletedBy  sql.NullInt64 `db:"deleted_by" gorm:"column:deleted_by"`
		Properties string        `db:"properties" gorm:"column:properties"`
		FileId     sql.NullInt64 `db:"file_id" gorm:"column:file_id"`
		CreatedAt  time.Time     `db:"created_at" gorm:"column:created_at"`
		UpdatedAt  time.Time     `db:"updated_at" gorm:"column:updated_at"`
		CreatedBy  uint64        `db:"created_by" gorm:"column:created_by"`
	}
)

func newWorkspaceLayerModel(conn *gorm.DB, connS sqlx.SqlConn) *defaultWorkspaceLayerModel {
	return &defaultWorkspaceLayerModel{
		DB:    conn,
		conn:  connS,
		table: "`workspace_layer`",
	}
}

func (m *defaultWorkspaceLayerModel) TableName() string {
	return m.table
}

// Delete 通过主键 id 删除数据，返回受影响行数
func (m *defaultWorkspaceLayerModel) Delete(ctx context.Context, id uint64) (int64, error) {
	logx.WithContext(ctx).Infof("delete data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("delete error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Delete(&WorkspaceLayer{})
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("delete error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

// FindOne 通过主键 id 查找数据
func (m *defaultWorkspaceLayerModel) FindOne(ctx context.Context, id uint64) (*WorkspaceLayer, error) {
	logx.WithContext(ctx).Infof("findOne data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("findOne error:%+v", "param invalid")
		return nil, InputParamInvalid
	}

	var result WorkspaceLayer
	err := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOne error:%+v", err)
		return nil, ReadDataFailed
	}

	return &result, nil
}

// FindByCanvasId 通过 canvas_id 查找所有未删除的图层
func (m *defaultWorkspaceLayerModel) FindByCanvasId(ctx context.Context, canvasId uint64) ([]*WorkspaceLayer, error) {
	logx.WithContext(ctx).Infof("findByCanvasId data:%+v", canvasId)

	if canvasId <= 0 {
		logx.WithContext(ctx).Errorf("findByCanvasId error:%+v", "param invalid")
		return nil, InputParamInvalid
	}

	var result []*WorkspaceLayer
	err := m.DB.Debug().WithContext(ctx).Where("`canvas_id` = ? AND `deleted` = FALSE", canvasId).Order("`z_index` ASC").Find(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return []*WorkspaceLayer{}, nil
		}
		logx.WithContext(ctx).Errorf("findByCanvasId error:%+v", err)
		return nil, ReadDataFailed
	}

	return result, nil
}

// FindDeletedByCanvasId 查找已删除的图层
func (m *defaultWorkspaceLayerModel) FindDeletedByCanvasId(ctx context.Context, canvasId uint64, limit int64) ([]*WorkspaceLayer, error) {
	logx.WithContext(ctx).Infof("findDeletedByCanvasId data:%+v", canvasId)

	if canvasId <= 0 {
		logx.WithContext(ctx).Errorf("findDeletedByCanvasId error:%+v", "param invalid")
		return nil, InputParamInvalid
	}

	var result []*WorkspaceLayer
	err := m.DB.Debug().WithContext(ctx).Where("`canvas_id` = ? AND `deleted` = TRUE", canvasId).
		Order("`deleted_at` DESC").Limit(int(limit)).Find(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return []*WorkspaceLayer{}, nil
		}
		logx.WithContext(ctx).Errorf("findDeletedByCanvasId error:%+v", err)
		return nil, ReadDataFailed
	}

	return result, nil
}

// Insert 插入数据，返回自增 id
func (m *defaultWorkspaceLayerModel) Insert(ctx context.Context, data *WorkspaceLayer) (int64, error) {
	logx.WithContext(ctx).Infof("insert data:%+v", data)

	result := m.DB.Debug().WithContext(ctx).Create(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return int64(data.Id), nil
}

// Restore 恢复已删除的数据
func (m *defaultWorkspaceLayerModel) Restore(ctx context.Context, id uint64) (int64, error) {
	logx.WithContext(ctx).Infof("restore data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("restore error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	updates := map[string]interface{}{
		"deleted":    false,
		"deleted_at": nil,
		"deleted_by": nil,
	}

	result := m.DB.Debug().WithContext(ctx).Model(&WorkspaceLayer{}).Where("`id` = ? AND `deleted` = TRUE", id).Updates(updates)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("restore error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

// SoftDelete 软删除图层
func (m *defaultWorkspaceLayerModel) SoftDelete(ctx context.Context, id uint64, deletedBy uint64) (int64, error) {
	logx.WithContext(ctx).Infof("softDelete data:%+v, deletedBy:%+v", id, deletedBy)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("softDelete error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	updates := map[string]interface{}{
		"deleted":    true,
		"deleted_at": time.Now(),
		"deleted_by": deletedBy,
	}

	result := m.DB.Debug().WithContext(ctx).Model(&WorkspaceLayer{}).Where("`id` = ? AND `deleted` = FALSE", id).Updates(updates)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("softDelete error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

// Update 通过主键 id 更新指定字段，零值不可更新，返回受影响行数
func (m *defaultWorkspaceLayerModel) Update(ctx context.Context, id int64, data *WorkspaceLayer) (int64, error) {
	logx.WithContext(ctx).Infof("update data:%+v", data)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("update error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Model(&WorkspaceLayer{}).Where("`id` = ?", id).Updates(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("update error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}
