// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"errors"

	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"gorm.io/gorm"
)

var _ WorkspaceCanvasModel = (*customWorkspaceCanvasModel)(nil)

type (
	// WorkspaceCanvasModel is an interface to be customized, add more methods here,
	// and implement the added methods in customWorkspaceCanvasModel.
	WorkspaceCanvasModel interface {
		workspaceCanvasModel
	}

	customWorkspaceCanvasModel struct {
		*defaultWorkspaceCanvasModel
	}
)

// NewWorkspaceCanvasModel returns a model for the database table.
func NewWorkspaceCanvasModel(conn *gorm.DB, connS sqlx.SqlConn) WorkspaceCanvasModel {
	return &customWorkspaceCanvasModel{
		defaultWorkspaceCanvasModel: newWorkspaceCanvasModel(conn, connS),
	}
}

var (
	workspaceCanvasFieldNames          = builder.RawFieldNames(&WorkspaceCanvas{})
	workspaceCanvasRows                = strings.Join(workspaceCanvasFieldNames, ",")
	workspaceCanvasRowsExpectAutoSet   = strings.Join(stringx.Remove(workspaceCanvasFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workspaceCanvasRowsWithPlaceHolder = strings.Join(stringx.Remove(workspaceCanvasFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	workspaceCanvasModel interface {
		// 返回的是受影响行数，如需获取自增 id，请通过 data 参数获取
		Insert(ctx context.Context, data *WorkspaceCanvas) (int64, error)
		FindOne(ctx context.Context, id uint64) (*WorkspaceCanvas, error)
		FindOneByProjectId(ctx context.Context, projectId uint64) (*WorkspaceCanvas, error)
		// 通过主键 id 更新指定字段，零值不可更新，返回受影响行数
		Update(ctx context.Context, id int64, data *WorkspaceCanvas) (int64, error)
		// 通过主键 id 删除数据，返回受影响行数
		Delete(ctx context.Context, id uint64) (int64, error)
	}

	defaultWorkspaceCanvasModel struct {
		DB    *gorm.DB
		conn  sqlx.SqlConn
		table string
	}

	WorkspaceCanvas struct {
		Id              uint64         `db:"id" gorm:"column:id;primaryKey"`
		ProjectId       uint64         `db:"project_id" gorm:"column:project_id"`
		Name            string         `db:"name" gorm:"column:name"`
		BackgroundColor string         `db:"background_color" gorm:"column:background_color"`
		Metadata        sql.NullString `db:"metadata" gorm:"column:metadata"`
		CreatedAt       time.Time      `db:"created_at" gorm:"column:created_at"`
		UpdatedAt       time.Time      `db:"updated_at" gorm:"column:updated_at"`
		CreatedBy       uint64         `db:"created_by" gorm:"column:created_by"`
	}
)

func newWorkspaceCanvasModel(conn *gorm.DB, connS sqlx.SqlConn) *defaultWorkspaceCanvasModel {
	return &defaultWorkspaceCanvasModel{
		DB:    conn,
		conn:  connS,
		table: "`workspace_canvas`",
	}
}

func (m *defaultWorkspaceCanvasModel) TableName() string {
	return m.table
}

// Delete 通过主键 id 删除数据，返回受影响行数
func (m *defaultWorkspaceCanvasModel) Delete(ctx context.Context, id uint64) (int64, error) {
	logx.WithContext(ctx).Infof("delete data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("delete error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).Delete(&WorkspaceCanvas{})
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("delete error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}

// FindOne 通过主键 id 查找数据
func (m *defaultWorkspaceCanvasModel) FindOne(ctx context.Context, id uint64) (*WorkspaceCanvas, error) {
	logx.WithContext(ctx).Infof("findOne data:%+v", id)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("findOne error:%+v", "param invalid")
		return nil, InputParamInvalid
	}

	var result WorkspaceCanvas
	err := m.DB.Debug().WithContext(ctx).Where("`id` = ?", id).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOne error:%+v", err)
		return nil, ReadDataFailed
	}

	return &result, nil
}

// FindOneByProjectId 通过 project_id 查找数据
func (m *defaultWorkspaceCanvasModel) FindOneByProjectId(ctx context.Context, projectId uint64) (*WorkspaceCanvas, error) {
	logx.WithContext(ctx).Infof("findOneByProjectId data:%+v", projectId)

	if projectId <= 0 {
		logx.WithContext(ctx).Errorf("findOneByProjectId error:%+v", "param invalid")
		return nil, InputParamInvalid
	}

	var result WorkspaceCanvas
	err := m.DB.Debug().WithContext(ctx).Where("`project_id` = ?", projectId).First(&result).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		logx.WithContext(ctx).Errorf("findOneByProjectId error:%+v", err)
		return nil, ReadDataFailed
	}

	return &result, nil
}

// Insert 插入数据，返回自增 id
func (m *defaultWorkspaceCanvasModel) Insert(ctx context.Context, data *WorkspaceCanvas) (int64, error) {
	logx.WithContext(ctx).Infof("insert data:%+v", data)

	result := m.DB.Debug().WithContext(ctx).Create(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("insert error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return int64(data.Id), nil
}

// Update 通过主键 id 更新指定字段，零值不可更新，返回受影响行数
func (m *defaultWorkspaceCanvasModel) Update(ctx context.Context, id int64, data *WorkspaceCanvas) (int64, error) {
	logx.WithContext(ctx).Infof("update data:%+v", data)

	if id <= 0 {
		logx.WithContext(ctx).Errorf("update error:%+v", "param invalid")
		return 0, InputParamInvalid
	}

	result := m.DB.Debug().WithContext(ctx).Model(&WorkspaceCanvas{}).Where("`id` = ?", id).Updates(data)
	if result.Error != nil {
		logx.WithContext(ctx).Errorf("update error:%+v", result.Error)
		return 0, WriteDataFailed
	}

	return result.RowsAffected, nil
}
